import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.css'; 
import { useEffect } from 'react';
import Accordion_item from "@/components/accordion-item";
import Lista_li from "@/components/Lista_li";
import Footer  from '@/components/foot';
import Card from '@/components/card';
import { useAutenticacao } from '@/conexao/autenticacaUser';



export default function Home() {
const { userId, logado } = useAutenticacao();

 
useEffect(() => { 


  import('bootstrap/dist/js/bootstrap').then(() => {
  }).catch((error) => {
  console.error('Erro ao carregar o Bootstrap:', error);
  });
 
  }, []);




return (
    <>  
  

<Head className="azul_fraco">
<title>Agencia viagem</title>
<meta name="description" content="Generated by create next app" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
</Head>



<header className=" text-center border-0  azul_fraco " >

<img src="img/FreeSpirit.svg" alt=""  width="20%"/>

{logado==false && 
<a href="autenticacao" class="float-end  border border-white text-white border-light   h4 d-inline btn btn-outline-primary">entra ou cadastra</a>
}

<ul className="nav justify-content-center bg-transparent text-center" style={{ top: '70%' }}>
<Lista_li link="#" nome_link="HOME"  />
<Lista_li link="destino" nome_link="DESTINO"  />
<Lista_li link="promocao" nome_link="PROMOCÃO"  />
<Lista_li link="contratado" nome_link="CONTRATADO"  />
</ul>

</header>
 

 
<div class="container-fluid position-relative p-0">
<img src="img/disney.jpeg" className="img-fluid " alt="..."/>
</div>





{logado &&

<div className="container-fluid bg-white" >
<h2>Pacotes contratados</h2> 
<div className='container'>
<div className="d-flex flex-wrap" >
  <Card    quantidade={2}   url={"pacotes_user/"+ userId}    userId={userId}      />
  

</div>
</div>
</div>

}
 

 

<div className="container-fluid bg-white" >
<h2>Principais pacotes</h2> 
<div className='container'>
<div className="d-flex flex-wrap" >

 
<Card   quantidade={5}   url="pacotes"   userId={logado == true? userId: null }        />

  

</div>
</div>
</div>














<div id="promocao" class="bg-white">
<div class="row mx-auto">
<h2>PROMOCÃO</h2>
<div className="col-sm-6 mb-3 mb-sm-0">
<div className="card">
<div className="card-body">
<h5 className="card-title">Viagen especial Disney <s>4000</s> por 2600  </h5>
<p className="card-text">Com direito a um acompanhante</p>
<a href="#" class="text-center" >ver</a><br/>
<a href="#" class="btn btn-primary">CONTRATAR</a>
</div>
</div>
</div>


<div className="col-sm-6">
<div className="card">
<div className="card-body">
<h5 className="card-title">Viagem em promoção Hawai <s>7000</s> por 3500</h5>
<p className="card-text">Por pessoas</p>
<a href="#" class="text-center" >ver</a><br/>
<a href="#" class="btn btn-primary">CONTRATAR</a>
</div>
</div>
</div>
</div>

	
<div className="  m-auto text-center p-0" >
<a href="promocao">mais promoções</a>
</div>
 </div>		










<div className='mb-4'>
<h2>Perguntas frequentes</h2>

<div className="accordion" id="accordionExample">
<Accordion_item  messagem="" titulo="Difculdade para viajar"/>

<Accordion_item  messagem="" titulo="Percas e roubos"/>








</div>
</div>
  <Footer/>

   


</>
  )
}
